"""add buy_price and sell_price to prices

Revision ID: 1eaf1135f65d
Revises: f8aed0791f1b
Create Date: 2026-05-24 00:00:25.296635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaf1135f65d'
down_revision: Union[str, Sequence[str], None] = 'f8aed0791f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sell_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_column('sell_price')
        batch_op.drop_column('buy_price')

    # ### end Alembic commands ###
