"""baseline schema

Revision ID: f8aed0791f1b
Revises: 
Create Date: 2026-05-23 23:59:38.919743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8aed0791f1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('maturity_date', sa.DateTime(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('interest_payout_frequency', sa.String(), nullable=False),
    sa.Column('interest_calculation_type', sa.String(), nullable=False),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixed_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixed_deposits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixed_deposits_institution_name'), ['institution_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixed_deposits_maturity_date'), ['maturity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixed_deposits_start_date'), ['start_date'], unique=False)

    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notify_days_before_30', sa.Boolean(), nullable=False),
    sa.Column('notify_days_before_7', sa.Boolean(), nullable=False),
    sa.Column('notify_on_maturity', sa.Boolean(), nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_trusts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_symbol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_trusts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_trusts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_trusts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_trusts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_trusts_symbol'), ['symbol'], unique=True)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixed_deposit_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('displayed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_deposit_id'], ['fixed_deposits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_fixed_deposit_id'), ['fixed_deposit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_status'), ['status'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_trust_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_trust_id'], ['unit_trusts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_trust_id', 'date', name='uq_unit_trust_date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_unit_trust_id'), ['unit_trust_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_trust_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('buy', 'sell', name='transaction_type_enum'), server_default='buy', nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_trust_id'], ['unit_trusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_unit_trust_id'), ['unit_trust_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_unit_trust_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_unit_trust_id'))
        batch_op.drop_index(batch_op.f('ix_prices_id'))
        batch_op.drop_index(batch_op.f('ix_prices_date'))

    op.drop_table('prices')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_fixed_deposit_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_created_at'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('unit_trusts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_trusts_symbol'))
        batch_op.drop_index(batch_op.f('ix_unit_trusts_provider'))
        batch_op.drop_index(batch_op.f('ix_unit_trusts_name'))
        batch_op.drop_index(batch_op.f('ix_unit_trusts_id'))

    op.drop_table('unit_trusts')
    op.drop_table('notification_settings')
    with op.batch_alter_table('fixed_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixed_deposits_start_date'))
        batch_op.drop_index(batch_op.f('ix_fixed_deposits_maturity_date'))
        batch_op.drop_index(batch_op.f('ix_fixed_deposits_institution_name'))
        batch_op.drop_index(batch_op.f('ix_fixed_deposits_id'))

    op.drop_table('fixed_deposits')
    # ### end Alembic commands ###
